"""add tle fields to satellites

Revision ID: 658b974a88db
Revises: 0bc905c535c9
Create Date: 2026-08-29 15:56:37.747424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658b974a88db'
down_revision: Union[str, Sequence[str], None] = '0bc905c535c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tle_line1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tle_line2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tle_updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('tle_updated_at')
        batch_op.drop_column('tle_line2')
        batch_op.drop_column('tle_line1')

    # ### end Alembic commands ###
