"""add expanded satellite metadata fields

Revision ID: 6d7cb68a9ca6
Revises: 27583a99ae77
Create Date: 2026-09-10 22:17:09.004682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7cb68a9ca6'
down_revision: Union[str, Sequence[str], None] = '27583a99ae77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('launch_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('satellite_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country_of_origin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('orbit_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.drop_column('orbit_type')
        batch_op.drop_column('country_of_origin')
        batch_op.drop_column('satellite_type')
        batch_op.drop_column('owner')
        batch_op.drop_column('launch_date')

    # ### end Alembic commands ###
