"""add image_pairs table

Revision ID: f1508b3b6db6
Revises: 738e20940486
Create Date: 2026-09-10 18:58:26.534494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1508b3b6db6'
down_revision: Union[str, Sequence[str], None] = '738e20940486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('before_image_id', sa.Integer(), nullable=False),
    sa.Column('after_image_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['after_image_id'], ['satellite_images.id'], ),
    sa.ForeignKeyConstraint(['before_image_id'], ['satellite_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_pairs')
    # ### end Alembic commands ###
